branches:
  except:
  - "/.*win.*/"
os: linux
dist: trusty
language: generic
before_install:
- echo `pwd`
- |
  echo ""
  echo "Installing a fresh version of Miniconda."
  MINICONDA_URL="https://repo.continuum.io/miniconda"
  MINICONDA_FILE="Miniconda3-latest-Linux-x86_64.sh"
  curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
  bash $MINICONDA_FILE -b
- |
  echo ""
  echo "Configuring conda."
  source /home/travis/miniconda3/bin/activate root
  conda config --remove channels defaults
  conda config --add channels defaults
  conda config --add channels conda-forge
  conda config --set show_channel_urls true
install:
- |
  conda install -y \
    jinja2 \
    pygit2 \
    click \
    jira \
    toolz \
    ruamel.yaml \
    setuptools_scm \
    github3.py \
    python-gnupg
script:
- pushd ..
- git clone -b master https://github.com/apache/arrow
- echo $TRAVIS_BUILD_DIR
- python arrow/dev/tasks/crossbow.py --queue-path $TRAVIS_BUILD_DIR submit --job-prefix
  nightly -g gandiva
env:
  global:
  - secure: iSAlVoNu+w7JkGcdEWwrII5KOFjNcNJyEjDn9hi6v05XyC7xp2JgePIeuZp2BjjpXTcCqVTmer/PgzHLvMKly6Sw5mP2UswXrl04LiDqVUWSrLZu5/9z4yTadmQWDQdShR8JpbvrA1fKn6hQpmRCfwkGqTeVHz/xj0CRg4Rp4bDFfTg/fP/xfXKm/1ccbjGzbIkm3/uYgA8G1NNbJCvPXQa97lnomy0v+gFwjDje/bnberLudG58XjuMZdAikdR154wrL8CuTTyVh4Bh9gvX1TXkI3kVW8Zo3csyvCS0PwSHMuWBK/JlNPj5+gjKOLa3tV1aK2NhE27L9IouyhVVkqUURRlIgmGzRqX2kNpU3HE0QU3a7PTYx1pqKJx2yJiSpKLKnciGYAzoXISkQvlIgeIAmyjUafeOMtmBPoT+IiVriizwjiqgPZXUjGiwH1O0pl6kqqrgRL4w5w0AiTHIFieVzinKHlgTHhYHsws7mMHYPJ8CyP2dNlidP9AXUTwLyW9vV+EJwtUoiy8JPv1a5TJIylpWVw7j9WcXImwU0/tVbKkpSi9fpLG5mzjULlTjk7b7FB84L+HLW3dfjvz4WG9sFOuLaVukESZO8v1+mmZpctFbwg0jnzf+QF/1EO3R9pI/2+9nJfNpmT5e67JGWAo727PW6t+i1soKiK1n3Zs=
  - secure: jH6oT4oQgx2lyLe3YXlDDL9lro1Xs47kInUZP9fWK3nxQVWvlPwxz3U+WdfwcouHpSDtAVEwfdyziMzgGg1J4NuZp5sjR2Vw63e29ZQDvBF5jipWOW7tNEX5jsQo7DWLQ8SN/RtmU1LCuNTs5elkwt+nK7kZccrnq8DYWG3qc3nt3nr7l07vxo2uleTV1/IhrTe3tIdwCXzSD6nqRiT306l7iCjXIsOzf0Muucz9i0RImhjm2xitUdEtOHr94eFVAf121TnAqzSzxVqv0mB04hMwDEfOm+4LzHe+On0ejnicxiRTvwagZnJ/qAIP/Da7eKVWhjhTlPgSsRSR+f8GzLTOAY0wem/q/ttf/W5X9H6VFhVRc3xeKJXGe523WrbFqsdsNGJKIj9Csa0/4Gim06amUd8OdyesUoBahZmbmxeV7ImUe8GqoOH9oWN3p/C8QDfPogD7CPE5Q9Cc0VobqW1ofvUgdK39vo6r9cbS2YTQFLS+s2X7D+Nl57/oA4IiAgOv1HASkhu7aGwAWYev49uWAQ6psie0nrQWhFAiZo5hqjOX42WcwmMMSIABcx3pGaPlymLmhLzzvCvgSYJ8VfUW2s7ltOjDe1obZub5ZwBod3CNbk1Xhby0OVHMn0dv2h9B2RBYOb515oZKmLCUBXqhYpJ1Jpqm/m/kGRGSVDY=
